### PR TITLE
Feat/editable list dropdown

### PR DESCRIPTION
**Pull request by jwinding**
## Explain the changes you’ve made

Add support for multiple choice dropdown inside the EditableList input component. 

## Explain your solution

Added it as a possible input type for the EditableList, and adjusted the layout slightly to avoid the label moving when opening the dropdown.
Added an option to make the select transparent, to improve how the component fits within editable list. 

## How to test the changes?

Go into the storybook and check the EditableList stories, in particular the one with different color schemas. The person field is a select. 

## Was this feature tested in the following environments?
- [x] Storybook on a iOS device/simulator.
- [] Building the Application on a iOS device/simulator.
- [] Building the Application on a Android device/simulator.

### CODE REVIEW

**Review by jonatanhanson — CHANGES_REQUESTED** [review]
It's working on iOS, but unfortunately nothing happens when clicking on the input field on Android.

**Comment by jwinding** [comment]
Seems like the problem is with the Select; it doesn't work in its own story on Android either, so that needs fixing.
Good find, I need to get in the habit of checking on both systems before making a PR.

**Comment by jwinding** [comment]
There is now a [PR](https://github.com/helsingborg-stad/app-mitt-helsingborg/pull/323) that fixes the problem of Select on android. Once that is merged, this can be rebased on top and then it should work (perhaps modulo some styling on android; that might be needed).

**Comment by jwinding** [comment]
Rebased this on top of develop after the android fix, so now it should work on both systems.

**Review by jonatanhanson — APPROVED** [review]
Its working on Android now 👍

**Pull request merged**
