### PR TITLE
Fixed proptypes for Banner.

### PR DESCRIPTION
**Pull request by zilaei**
Setting prop types to corresponds to what Step.js passes down: Array with style object.

### CODE REVIEW

**Review by jonatanhanson — APPROVED** [review]

**Review by TeddyAndersson — APPROVED** [review]

**Review by jwinding — APPROVED** [review]

**Review by dannil76 — APPROVED** [review]
Works!

**Comment by TeddyAndersson** [comment]
@zilaei are you working on the img fix on this PR or can we merge/rebase this PR?

**Comment by TeddyAndersson** [comment]
> @zilaei are you working on the img fix on this PR or can we merge/rebase this PR?

Feels like the img bug is another PR in my opinon, since this relates to propTypes and not img not rendering (y)

**Comment by zilaei** [comment]
Img bug will be fixed on another PR. Sorry for the late reply.

**Pull request merged**
