### PR TITLE
Feat/display case decision

### PR DESCRIPTION
**Pull request by jonatanhanson**
## Explain the changes you’ve made

Added functionality to display VIVA case data:
-  Decisions
- Calculations
- Detailed calculations
- Payments

## Explain your solution

Display payments data within a Card component from the case detail screen. 
Added modal to the case detail screen with decision and calculations data. 

See this as iteration 1 because i didnt have any design to follow. So the design needs to be implemented later and then the code can also be refactored.

## How to test the changes?

Add mocked cases with workflows to your database.
JSON files with mockdata can be found here: https://app.clickup.com/t/eq1fwu

Click on a rejected or approved case from case overview screen.
On the approved case there will be a card component showing payments.
Click on "Visa beslut" and it will show a modal with decision and calculations data.
Grab a beer, its friday 🍺 

## Was this feature tested in the following environments?
- [] Storybook on a iOS device/simulator.
- [X] Building the Application on a iOS device/simulator.
- [X] Building the Application on a Android device/simulator.

## Screenshots
Screenshot 2021-02-26 at 08 35 15
Screenshot 2021-02-26 at 08 35 24
Screenshot 2021-02-26 at 08 35 34

## Anyhting else?
There is some data and acronyms in the calculations that I don't know how to handle and needs to be fixed.

### CODE REVIEW

**Comment by helsingborgsstad** [comment]
Task linked: [CU-eq1fwu Löpande: Visa upp resultat från beräkning i App](https://app.clickup.com/t/eq1fwu)

**Review by jwinding — APPROVED** [review]
Works, and looks really good, I think; almost no need for extra designwork. 

Only comment on the code is that the CaseOverview file is getting really long, so perhaps it could be broken up a bit? Like, the computeCaseCardComponent is really its own component, and could be broken out into its own file. Likewise, the content inside the modal could potentially also be its own component and be broken out. This is not so important though.

**Comment by jonatanhanson** [comment]
> Works, and looks really good, I think; almost no need for extra designwork.
> 
> Only comment on the code is that the CaseOverview file is getting really long, so perhaps it could be broken up a bit? Like, the computeCaseCardComponent is really its own component, and could be broken out into its own file. Likewise, the content inside the modal could potentially also be its own component and be broken out. This is not so important though.

That is correct it needs to be done, the render part is massive. Not sure if i will do it now or after the new design implementation, we'll see.

**Review by zilaei — APPROVED** [review]
Sweet!

**Review by dannil76 — APPROVED** [review]

**Pull request merged**
