### PR TITLE
🐛 Fix bug where image wasn't readable in viva (#CU-1e6mzqy)

### PR DESCRIPTION
**Pull request by Sven65**
## Explain the changes you’ve made

I've removed the maximum dimensions for the image picker as the cropping causes the images to become unreadable. More info available at #CU-1e6mzqy

## Explain why these changes are made

To facilitate readability of images

## How to test the changes?

Concrete example:
1. Checkout this branch
2. Start a stickprov
3. Upload an image
4. Open the image in S3
5. See that it's readable.

## Was this feature tested in the following environments?
- [] Storybook on a iOS device/simulator.
- [x] Building the Application on a iOS device/simulator.
- [] Building the Application on a Android device/simulator.

## Anything else? (optional)

I'm unsure if this is the best way to go about this issue, as it does increase the file size on S3.

### CODE REVIEW

**Comment by helsingborgsstad** [comment]
Task linked: [CU-1e6mzqy Bifogad bild ej läsbar i Viva](https://app.clickup.com/t/1e6mzqy)

**Comment by helsingborgsstad** [comment]
Task linked: [CU-1e6u56x Skärmdumpar vid filuppladdning för stickprov komprimeras för mycket](https://app.clickup.com/t/1e6u56x)

**Review by KenthLjungHBG — COMMENTED** [review]
Solution seems fine in theory, but I'm wondering if there are issues with uploading too big (dimension-wise) images with this? Maybe @dannil76 knows; I haven't tested yet.

**Review by dannil76 — APPROVED** [review]
If you refer to Viva-admin, I'm not 100% sure there is an limit size-wise?
Let's try it and see

**Pull request merged**
