### PR TITLE
fix(validation): a few small fixes of validation behaviour

### PR DESCRIPTION
**Pull request by jwinding**
## Explain the changes you’ve made

Two small fixes to validation behaviour. Fixes the validation of required checkboxes so that they display an error if the user toggles them on and then off again. Secondly, fixes the behaviour of validation of editable list, so that it doesn't display errors on fields the user has not touched. 

Also fixes the format of initial answers object when starting a new form from the dev-screen. 

## Explain your solution

The Checkbox was never set as dirty, which meant that no validation error was displayed until the user tried to go to the next screen (which dirties all fields on the step). This is fixed by giving it an 'onBlur' behaviour that triggers when the user clicks it, which in turn means that it is dirtied as soon as the user clicks it. 

The editable list also had trouble with validation of non-dirty fields behaving wrong. This was because when validating from an onBlur event, we didn't check if the field was dirty, which we should be doing. So here I just changed the order so that we first dirty the field, and then only validate dirty field also when it is triggered by an onBlur event.

Finally, when starting a new form, the FormCaseScreen was setting the answers-object as an array, rather than an object, which lead to weird behaviour. This only triggers when starting new cases from the developer screen. 

## How to test the changes?

Checkout this branch, and go into the test-form on Development. Try toggling the checkbox on the first page, it's marked as required and should thus display an error when empty (after having been toggled). 

Also try the editable list of personal info. Every field except the first is marked as required, so check that the validation errors only show up after a field has been touched by the user. Also try the validation in general, check that nothing else was broken by these changes. 

## Was this feature tested in the following environments?
- [] Storybook on a iOS device/simulator.
- [] Building the Application on a iOS device/simulator.
- [x] Building the Application on a Android device/simulator.

### CODE REVIEW

**Comment by helsingborgsstad** [comment]
Task linked: [CU-dx444b Validering: Checkbox required och Editable list beteende](https://app.clickup.com/t/dx444b)

**Review by zilaei — APPROVED** [review]
It works!

**Review by jonatanhanson — APPROVED** [review]
Works as intended 👍

**Comment by helsingborgsstad** [comment]
Task linked: [CU-dx3kd1 Appen kraschar vid start av nytt ärende](https://app.clickup.com/t/dx3kd1)

**Pull request merged**
