### PR TITLE
Feat/case summary administrators

### PR DESCRIPTION
**Pull request by jonatanhanson**
## Explain the changes you’ve made

- Implemented new contact persons style in case summary view.
- Added helper function to launch phone app.
- Added helper function to launch email app.

**NOTE**
**The iOS simulator does not support triggering phone call or mail feature. Only works on an actual device.. or Android .** 

## Explain why these changes are made

Implemented latest designs. 

## Explain your solution

Changed the layout of the contact cards and added phone call and mail features as a helper. 

## How to test the changes?

Go to app home screen (Case overview).
Enter case summary screen by clicking on an ongoing or submitted case. 
If the case has any administrators in it's data, it will be showing as contact cards in the view.
Test hitting mail and phone buttons and see if everything works as expected.

## Was this feature tested in the following environments?
- [] Storybook on a iOS device/simulator.
- [] Building the Application on a iOS device/simulator.
- [X] Building the Application on a Android device/simulator.

## Screenshots (optional)

Simulator Screen Shot - iPhone 11 - 2020-11-24 at 14 45 17

### CODE REVIEW

**Comment by zilaei** [comment]
Which user and case should I test this feature with?

**Review by dannil76 — COMMENTED** [review]
Got this error when clicked on case in overview list
Skärmavbild 2020-11-26 kl  07 32 01

**Comment by jonatanhanson** [comment]
> Which user and case should I test this feature with?

You need to run the latest AWS environment. Then it should work with any form.

**Comment by dannil76** [comment]
Works better now!
When clicking on email at the detail view I got log error
Error: Failed to launch email app

Not sure if this is bad...

**Review by dannil76 — APPROVED** [review]

**Pull request merged**
