### PR TITLE
Feat/pdf uploader

### PR DESCRIPTION
**Pull request by jwinding**
## Explain the changes you’ve made

Add components for handling PDFs, very similar to the way we upload images. 

## Explain why these changes are made

We seem to need the functionality for Stickprov.

## Explain your solution

Basically, I'm doing the exact same thing for PDFs as previously done for images. 

Same overall structure of components, with a PdfItem responsible for displaying the preview and detailed view of a PDF, and a Display component that displays a list of PdfItems. An Upload component that lets the user attach PDFs, and a Viewer that lets us show uploaded pdfs in a summary. 

Under the hood there are various things that are different, since other libraries needs to be used to display and pick PDFs compared to Images. There's also some small changes to the uploadFile helper, to handle the MIME-type for pdfs correctly. 

If people think it is warranted, one could quite easily abstract this a bit, and unify the image and pdf handling, so that some of the display code can be reused. However, I felt like making it work first, and it probably becomes a little harder to understand if such a generalization is made. 

## How to test the changes?

Checkout the branch, then run yarn to install new packages. On iOS, you need to run pod install. Then rebuild the app.

In dev, in the form for testing ImageUploader, I've added the PdfUploader component on the first page, and the viewer on the second page. To test it, you need to download one or a few pdfs to your phone/emulator, and then try and add them. Then check that they show up correctly, that pressing the thumbnail opens a modal that lets you scroll and zoom. Also check that they arrive correctly in the S3, and so on. 

## Was this feature tested in the following environments?
- [] Storybook on a iOS device/simulator.
- [] Building the Application on a iOS device/simulator.
- [x] Building the Application on a Android device/simulator.

## Screenshots (optional)
pdfUploader

### CODE REVIEW

**Comment by helsingborgsstad** [comment]
Task linked: [CU-ed2q0k Komponent för uppladdning av PDF-dokument](https://app.clickup.com/t/ed2q0k)

**Comment by nRamstedt** [comment]
I'm having a hard time building this in xcode.

I tried:

- Checking out this branch and clean up watchman, node_modules, pods & DerivedData folder
- Checking out this branch (rebased on dev) and clean up watchman, node_modules, pods & DerivedData folder
- Checking out latest dev without these commits and it works

Seems to be some issue with new dependecies

**Comment by jonatanhanson** [comment]
> I'm having a hard time building this in xcode (IOS Simulator).
> 
> I tried:
> 
>     * Checking out this branch and clean up watchman, node_modules, pods & DerivedData folder
> 
>     * Checking out this branch (rebased on dev) and clean up watchman, node_modules, pods & DerivedData folder
> 
>     * Checking out latest dev without these commits and it works
> 
> 
> Seems to be some issue with new dependecies

Kan inte heller bygga appen, har nog något med xcode-filerna att göra. Jacob kan du testa bygga om denna branchen och se om det funkar för dig?

**Comment by zilaei** [comment]
Lyckats fixa bygget för iOS, kan pusha fix till denna branch om det är okej @jwinding?

**Comment by jwinding** [comment]
> Lyckats fixa bygget för iOS, kan pusha fix till denna branch om det är okej @jwinding?

Absolut! Jag har också precis fått till det, men det känns som min ios miljö är konstig (vilket var vad som orsakade felet till att börja med, tror jag, råkade pusha upp en förstörd .xcodeproj fil), så jättebra om du har fått till det! Pusha på, alltså.

**Comment by zilaei** [comment]
> > I'm having a hard time building this in xcode (IOS Simulator).
> > I tried:
> > ```
> > * Checking out this branch and clean up watchman, node_modules, pods & DerivedData folder
> > 
> > * Checking out this branch (rebased on dev) and clean up watchman, node_modules, pods & DerivedData folder
> > 
> > * Checking out latest dev without these commits and it works
> > ```
> > 
> > 
> > Seems to be some issue with new dependecies
> 
> Kan inte heller bygga appen, har nog något med xcode-filerna att göra. Jacob kan du testa bygga om denna branchen och se om det funkar för dig?

Prova gärna bygga om för iOS, kolla även fonter och att dom fortfarande ser bra ut med fixen.

**Review by zilaei — APPROVED** [review]
Nice!

**Comment by nRamstedt** [comment]
Building works! Can't manage to download pdfs on my simulator.. will try build on my device instead. Found this error in simulator though, when opening upload modal and closing (without adding any files) trigger an error (does not make the app crash though).

**Comment by zilaei** [comment]
> Building works! Can't manage to download pdfs on my simulator.. will try build on my device instead. Found this error in simulator though, when opening upload modal and closing (without adding any files) trigger an error (does not make the app crash though).
> 
> Uploading Skärmavbild 2021-03-01 kl. 13.39.08.png…

Good catch! I'm seeing the same error when closing modal.

**Pull request merged**
