### PR TITLE
Checks for handling missing question ID

### PR DESCRIPTION
**Pull request by zilaei**
Added checks for missing question ID.
Test by stepping through a form (ex. Ekonomiskt bistånd löpande ansökan, nya steg-logiken). The form will crash before this fix on the first quintet.

### CODE REVIEW

**Review by dannil76 — CHANGES_REQUESTED** [review]
Have trouble runnig the app.
See screendumps
Skärmavbild 2020-10-29 kl  14 55 04
Skärmavbild 2020-10-29 kl  14 55 17

**Comment by TeddyAndersson** [comment]
Got this working in Storybook just fine (y)
Will test building the application and opening a form there aswell :)

**Comment by TeddyAndersson** [comment]
Bulding the application also works as expected (y)

**Review by TeddyAndersson — APPROVED** [review]

**Comment by TeddyAndersson** [comment]
> Have trouble runnig the app.
> See screendumps
> Skärmavbild 2020-10-29 kl 14 55 04
> Skärmavbild 2020-10-29 kl 14 55 17

Looks like this have something to do with the build of the app, my enviorment works just fine. Therefore i approve this PR. If you don't have any problems with that Dan :)

**Comment by dannil76** [comment]
Cool! Let's go for dev

**Review by dannil76 — APPROVED** [review]

**Pull request merged**
