### PR TITLE
Bug/onboarding corrections

### PR DESCRIPTION
**Pull request by Sven65**
## Explain the changes you’ve made

This pull request consists of three tasks, #CU-g57e7g, #CU-mf9rap and #CU-k3bfqa

- I've changed the "m" in "mobilt BankID" to be capitalized, i.e "Mobilt" instead of "mobilt" on the login screen. (#CU-g57e7g)
- I've changed the way headers are wrapped in the onboarding view in order to fit all the text. (#CU-mf9rap)
- I've added a skip button to the onboarding views. (#CU-k3bfqa)

## How to test the changes?

Concrete example:
1. Checkout this branch
2. See that things are changed

## Was this feature tested in the following environments?
- [] Storybook on a iOS device/simulator.
- [x] Building the Application on a iOS device/simulator.
- [] Building the Application on a Android device/simulator.

### CODE REVIEW

**Comment by helsingborgsstad** [comment]
Task linked: [CU-k3bfqa On-boarding: Skip-knapp saknas](https://app.clickup.com/t/k3bfqa)

**Comment by helsingborgsstad** [comment]
Task linked: [CU-g57e7g Under Fler Alternativ - inloggning: stort M på "Mobilt BankID"](https://app.clickup.com/t/g57e7g)

**Comment by helsingborgsstad** [comment]
Task linked: [CU-mf9rap On-boardingskärm nr 3 syns inte text](https://app.clickup.com/t/mf9rap)

**Review by zilaei — APPROVED** [review]
👍

**Pull request merged**
